name: Test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - 'poetry.lock'
      - '{{ cookiecutter.plugin.lower().replace('-','_') }}/**'
      - 'tests/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/test.yaml'
      - 'poetry.lock'
      - '{{ cookiecutter.plugin.lower().replace('-','_') }}/**'
      - 'tests/**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: {{ "${{ matrix.python-version }}" }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: {{ "${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}" }}
      - name: "Setup Poetry"
        run: |
          pip install --upgrade pip
          pip install --user poetry
          poetry install
      - name: "Generate Coverage Report"
        run: poetry run pytest --cov --cov-report=xml -n auto
      # - name: "Upload to Codecov.io"
      #   if: github.repository == '{{ cookiecutter.username }}/{{ cookiecutter.plugin }}' && github.event_name != 'pull_request'
      #   uses: codecov/codecov-action@v2
      #   with:
      #     fail_ci_if_error: true
