ci:
  autofix_commit_msg: "ci: pre-commit auto fixes"
  autoupdate_commit_msg: "ci: pre-commit auto update"
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.35.0
    hooks:
      - id: nitpick-check
        name: Nitpick Check
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.6
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.21.0
    hooks:
      - id: typos
        name: Check Typos
        args: []
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Type Check
        args: []
        # As `mypy` runs in an isolated environment, it is necessary to manually specify
        # some libraries of the current (poetry) environment for `mypy` to work properly.
        additional_dependencies:
          - pytest==6.2.5
          - rsserpent-rev>=0.1.4
          - types-lxml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]