[tool.poetry]
name = "{{ cookiecutter.plugin }}"
version = "0.1.0"

authors = ["{{ cookiecutter.username }} <{{ cookiecutter.email }}>"]
description = "{{ cookiecutter.description }}"
keywords = ["rss"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rsserpent-rev = ">=0.1.4"

[tool.poetry.dev-dependencies]
pre-commit = "^2.15.0"
uvicorn = "^0.29.0"
# testing
pytest = "^8.0"
pytest-asyncio = "^0.15.1"
pytest-cov = "^3.0.0"
pytest-randomly = "^3.10.1"
pytest-xdist = "^2.3.0"
requests = "^2.26.0"

[tool.poetry.plugins."rsserpent.plugin"]
"{{ cookiecutter.plugin.removeprefix('rsserpent-plugin-') }}" = "{{ cookiecutter.plugin.lower().replace('-','_') }}:plugin"

[tool.black]
include = '\.pyi?$'
target-version = ["py310"]

[tool.coverage.run]
include = ["{{ cookiecutter.plugin.lower().replace('-','_') }}/*"]

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",
    "pragma: no cover"
]

[tool.isort]
balanced_wrapping = true
combine_as_imports = true
lines_after_imports = 2
profile = "black"

[tool.nitpick]
style = "https://raw.githubusercontent.com/RSSerpent-Rev/RSSerpent/master/styles/main.toml"
cache = "1 day"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"
